language: node_js
node_js:
  - '10'
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - cd what-zen
  - npm ci
before_install:
  - 'npm install -g npm@6'
before_script:
  - sleep 15
script:
  - npm start
  - $cypress
  - $(npm bin)/cypress run --record
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
