language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - cd what-zen
  - npm ci
  - npm install start-server-and-test
before_install:
  - 'npm install -g npm@6'
before_script:
  - npm start -- --silent &
script:
  - cypress run --record
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
